import { Router } from "express";
import { analyticsRoutes } from "./analytics/analytics.routes";
import { authRoutes } from "./auth/auth.routes";
import { usersRoutes } from "./users/users.routes";
import { sampleEntityRoutes } from "./sample-entity/sample-entity.routes";
import { reportsRoutes } from "./reports/reports.routes";
import { departmentsRoutes } from "./departments/departments.routes";
import { categoriesRoutes } from "./categories/categories.routes";
import { assetsRoutes } from "./assets/assets.routes";
import { allocationsRoutes } from "./allocations/allocations.routes";
import { transfersRoutes } from "./transfers/transfers.routes";
import { bookingsRoutes } from "./bookings/bookings.routes";
import { maintenanceRoutes } from "./maintenance/maintenance.routes";
import { auditsRoutes } from "./audits/audits.routes";
import { notificationsRoutes } from "./notifications/notifications.routes";
import { dashboardRoutes } from "./dashboard/dashboard.routes";

export const apiRouter = Router();

apiRouter.use("/auth", authRoutes);
apiRouter.use("/analytics", analyticsRoutes);
apiRouter.use("/reports", reportsRoutes);
apiRouter.use("/users", usersRoutes);
apiRouter.use("/sample-entities", sampleEntityRoutes);
apiRouter.use("/departments", departmentsRoutes);
apiRouter.use("/categories", categoriesRoutes);
apiRouter.use("/assets", assetsRoutes);
apiRouter.use("/allocations", allocationsRoutes);
apiRouter.use("/transfers", transfersRoutes);
apiRouter.use("/bookings", bookingsRoutes);
apiRouter.use("/maintenance", maintenanceRoutes);
apiRouter.use("/audits", auditsRoutes);
apiRouter.use("/notifications", notificationsRoutes);
apiRouter.use("/dashboard", dashboardRoutes);
